### PR TITLE
user stories

### PR DESCRIPTION
**Pull request by haihau**
Plz take look and tell me what I should add.

### CODE REVIEW

**Comment by DanthakaSri** [comment]
[User Stories.docx](https://github.com/chrishanpeiris/cdu-mas/files/1832074/User.Stories.docx)
Hi @haihau , I have attached a user stories document. Please go through the document and comment the required changes.

**Comment by chrishanpeiris** [comment]
Looks fine.

**Comment by DanthakaSri** [comment]
This is confirmed as our user stories, I'll submit it on learnline

**Comment by haihau** [comment]
[User.Stories .docx](https://github.com/chrishanpeiris/cdu-mas/files/1832920/User.Stories.docx)
I had updated the user story document

**Pull request closed without merging**
